drop table zxidc_dbms.IDC_TICKET_HIS ;
drop table zxidc_dbms.IDC_TICKET_TEST ;
drop table zxidc_dbms.IDC_TICKET_RUN ;
drop table zxidc_dbms.idc_re_product;

 create table zxidc_dbms.idc_re_product(id NUMBER(20) not null, apply_id NUMBER(20), apply_name VARCHAR2(30 char), apply_phone VARCHAR2(30 char), apply_roles VARCHAR2(255 char), bus_name varchar2(255 char), create_time TIMESTAMP(6) DEFAULT SYSTIMESTAMP, customer_id NUMBER(20), customer_name VARCHAR2(255 char), idc_code varchar2(255 char), idc_name varchar2(255 char), is_active NUMBER(2) DEFAULT 0, proc_ticket_status number(10,0), prod_category number(10,0), prod_name varchar2(255 char), prod_status number(10,0), region_id number(19,0), region_name varchar2(255 char), validity varchar2(255 char), primary key (id))
 create table zxidc_dbms.idc_ticket_his(id number(19,0) not null, apply_id number(19,0), apply_name varchar2(255 char), audit_ids varchar2(255 char), audit_name varchar2(255 char), bus_name varchar2(255 char), candidate varchar2(255 char), candidate_ids varchar2(255 char), confirm_status NUMBER(2) DEFAULT 0, create_time TIMESTAMP(6) DEFAULT SYSTIMESTAMP, customer_id number(19,0), customer_manager_id number(19,0), customer_manager_name varchar2(255 char), customer_name varchar2(255 char), end_time timestamp, form_key varchar2(255 char), idc_code varchar2(255 char), idc_name varchar2(255 char), is_relevant_ticket NUMBER(2) DEFAULT 0, parent_id NUMBER(20) DEFAULT -1, proc_def_key varchar2(255 char), proc_inst_id varchar2(255 char), prod_category number(10,0), prod_inst_id number(19,0), region_id number(19,0), region_name varchar2(255 char), res_allocation_status number(1,0), role_key varchar2(255 char), root_id number(19,0), serial_number varchar2(255 char), sp_status number(10,0), task_id varchar2(255 char), task_name varchar2(255 char), ticket_category varchar2(255 char), ticket_category_from varchar2(255 char), ticket_category_to varchar2(255 char), ticket_res_hand_status NUMBER(1) DEFAULT 0, ticket_status NUMBER(4) DEFAULT 0, ticket_update_status NUMBER(1) DEFAULT 0, update_time timestamp, primary key (id))
 create table zxidc_dbms.idc_ticket_run(id number(19,0) not null, apply_id number(19,0), apply_name varchar2(255 char), audit_ids varchar2(255 char), audit_name varchar2(255 char), bus_name varchar2(255 char), candidate varchar2(255 char), candidate_ids varchar2(255 char), confirm_status NUMBER(2) DEFAULT 0, create_time TIMESTAMP(6) DEFAULT SYSTIMESTAMP, customer_id number(19,0), customer_manager_id number(19,0), customer_manager_name varchar2(255 char), customer_name varchar2(255 char), end_time timestamp, form_key varchar2(255 char), idc_code varchar2(255 char), idc_name varchar2(255 char), is_relevant_ticket NUMBER(2) DEFAULT 0, parent_id NUMBER(20) DEFAULT -1, proc_def_key varchar2(255 char), proc_inst_id varchar2(255 char), prod_category number(10,0), prod_inst_id number(19,0), region_id number(19,0), region_name varchar2(255 char), res_allocation_status number(1,0), role_key varchar2(255 char), root_id number(19,0), serial_number varchar2(255 char), sp_status number(10,0), task_id varchar2(255 char), task_name varchar2(255 char), ticket_category varchar2(255 char), ticket_category_from varchar2(255 char), ticket_category_to varchar2(255 char), ticket_res_hand_status NUMBER(1) DEFAULT 0, ticket_status NUMBER(4) DEFAULT 0, ticket_update_status NUMBER(1) DEFAULT 0, update_time timestamp, primary key (id))
 create table zxidc_dbms.idc_ticket_test(id number(19,0) not null, prod_inst_id number(19,0), test_end_time timestamp, test_start_time timestamp, ticket_inst_id number(19,0), validity varchar2(255 char), primary key (id))

COMMENT ON TABLE IDC_RE_PRODUCT is '订单产品表';
comment on column IDC_RE_PRODUCT.ID is '主键';
comment on column IDC_RE_PRODUCT.APPLY_ID is '申请人主键';
comment on column IDC_RE_PRODUCT.APPLY_NAME is '申请人名称';
comment on column IDC_RE_PRODUCT.APPLY_PHONE is '申请人电话';
comment on column IDC_RE_PRODUCT.APPLY_ROLES is '申请人角色';
comment on column IDC_RE_PRODUCT.CREATE_TIME is '创建时间';
comment on column IDC_RE_PRODUCT.CUSTOMER_ID is '所属客户主键';
comment on column IDC_RE_PRODUCT.CUSTOMER_NAME is '客户名称';
comment on column IDC_RE_PRODUCT.IS_ACTIVE is '1激活;0禁用';
comment on column IDC_RE_PRODUCT.PROD_STATUS is '订单状态,dict:10,在途;20,已竣工;30,已停机;40,已撤销';
comment on column IDC_RE_PRODUCT.PROC_TICKET_STATUS is '流程工单状态:10草稿；20预勘中，21已经预勘；30开通中，31已经开通；40停机中，41已经停机；50下线中，51已经下线；60变更中，61已经变更;70复通中，71复通完成';
comment on column IDC_RE_PRODUCT.PROD_CATEGORY is '订单类别:1普通业务0自有业务';
comment on column IDC_RE_PRODUCT.PROD_NAME is '订单实例名称';
comment on column IDC_RE_PRODUCT.IDC_CODE is '意向IDC的标识';
comment on column IDC_RE_PRODUCT.IDC_NAME is '意向IDC的名字';
comment on column IDC_RE_PRODUCT.REGION_ID is '区域';
comment on column IDC_RE_PRODUCT.REGION_NAME is '区域名称';
comment on column IDC_RE_PRODUCT.BUS_NAME is '业务名称';
comment on column IDC_RE_PRODUCT.VALIDITY is '预占有效期（天）';
COMMENT ON TABLE IDC_TICKET_HIS is '历史工单';
comment on column IDC_TICKET_HIS.ID is '主键';
comment on column IDC_TICKET_HIS.CUSTOMER_MANAGER_ID is '客户经理';
comment on column IDC_TICKET_HIS.CUSTOMER_MANAGER_NAME is '客户经理名称';
comment on column IDC_TICKET_HIS.APPLY_ID is '申请人';
comment on column IDC_TICKET_HIS.APPLY_NAME is '申请名称';
comment on column IDC_TICKET_HIS.AUDIT_IDS is '审批过的人主键';
comment on column IDC_TICKET_HIS.AUDIT_NAME is '审批过的名称';
comment on column IDC_TICKET_HIS.BUS_NAME is '业务名称';
comment on column IDC_TICKET_HIS.CANDIDATE is '候选审批人';
comment on column IDC_TICKET_HIS.CANDIDATE_IDS is '候选审批人主键';
comment on column IDC_TICKET_HIS.CREATE_TIME is '创建日期';
comment on column IDC_TICKET_HIS.CUSTOMER_ID is '客户主键';
comment on column IDC_TICKET_HIS.CUSTOMER_NAME is '客户名';
comment on column IDC_TICKET_HIS.END_TIME is '结束时间';
comment on column IDC_TICKET_HIS.FORM_KEY is '表单标识';
comment on column IDC_TICKET_HIS.IS_RELEVANT_TICKET is '是否存在相关工单0不存在，1存在';
comment on column IDC_TICKET_HIS.PARENT_ID is '父工单';
comment on column IDC_TICKET_HIS.PROC_DEF_KEY is '流程定义标识';
comment on column IDC_TICKET_HIS.PROC_INST_ID is '关联流程实例主键';
comment on column IDC_TICKET_HIS.PROD_CATEGORY is '产品类型';
comment on column IDC_TICKET_HIS.PROD_INST_ID is '关联产品实例主键';
comment on column IDC_TICKET_HIS.RES_ALLOCATION_STATUS is '显示资源分配 1:可以查看资源分配，0不能查看资源分配';
comment on column IDC_TICKET_HIS.ROLE_KEY is '候选审批角色标识';
comment on column IDC_TICKET_HIS.SERIAL_NUMBER is '工单编号';
comment on column IDC_TICKET_HIS.TASK_ID is '任务主键';
comment on column IDC_TICKET_HIS.TASK_NAME is '任务名称';
comment on column IDC_TICKET_HIS.TICKET_UPDATE_STATUS is '工单是否可修改表单需求';
comment on column IDC_TICKET_HIS.TICKET_CATEGORY is '工单类型';
comment on column IDC_TICKET_HIS.TICKET_CATEGORY_FROM is '主键';
comment on column IDC_TICKET_HIS.TICKET_CATEGORY_TO is '主键';
comment on column IDC_TICKET_HIS.TICKET_RES_HAND_STATUS is '工单资源是否可编辑';
comment on column IDC_TICKET_HIS.TICKET_STATUS is '工单状态 0初始化、1运行中、-2作废、-3删除到回收站、2结束、-22作废结束、-23删除结束';
comment on column IDC_TICKET_HIS.SP_STATUS is '审批状态 -1不同意/驳回';
comment on column IDC_TICKET_HIS.IDC_CODE is '意向IDC的标识';
comment on column IDC_TICKET_HIS.REGION_ID is '工单所属区域主键';
comment on column IDC_TICKET_HIS.IDC_NAME is '意向IDC的名称';
comment on column IDC_TICKET_HIS.REGION_NAME is '工单所属区域名称';
comment on column IDC_TICKET_HIS.ROOT_ID is '受理工单主键';
comment on column IDC_TICKET_HIS.UPDATE_TIME is '修改日期';
comment on column IDC_TICKET_HIS.CONFIRM_STATUS is '确认状态';
COMMENT ON TABLE IDC_TICKET_RUN is '运行工单';
comment on column IDC_TICKET_RUN.ID is '主键';
comment on column IDC_TICKET_RUN.CUSTOMER_MANAGER_ID is '客户经理';
comment on column IDC_TICKET_RUN.CUSTOMER_MANAGER_NAME is '客户经理名称';
comment on column IDC_TICKET_RUN.APPLY_ID is '申请人';
comment on column IDC_TICKET_RUN.APPLY_NAME is '申请名称';
comment on column IDC_TICKET_RUN.AUDIT_IDS is '审批过的人主键';
comment on column IDC_TICKET_RUN.AUDIT_NAME is '审批过的名称';
comment on column IDC_TICKET_RUN.BUS_NAME is '业务名称';
comment on column IDC_TICKET_RUN.CANDIDATE is '候选审批人';
comment on column IDC_TICKET_RUN.CANDIDATE_IDS is '候选审批人主键';
comment on column IDC_TICKET_RUN.CREATE_TIME is '创建日期';
comment on column IDC_TICKET_RUN.CUSTOMER_ID is '客户主键';
comment on column IDC_TICKET_RUN.CUSTOMER_NAME is '客户名';
comment on column IDC_TICKET_RUN.END_TIME is '结束时间';
comment on column IDC_TICKET_RUN.FORM_KEY is '表单标识';
comment on column IDC_TICKET_RUN.IS_RELEVANT_TICKET is '是否存在相关工单0不存在，1存在';
comment on column IDC_TICKET_RUN.PARENT_ID is '父工单';
comment on column IDC_TICKET_RUN.PROC_DEF_KEY is '流程定义标识';
comment on column IDC_TICKET_RUN.PROC_INST_ID is '关联流程实例主键';
comment on column IDC_TICKET_RUN.PROD_CATEGORY is '产品类型';
comment on column IDC_TICKET_RUN.PROD_INST_ID is '关联产品实例主键';
comment on column IDC_TICKET_RUN.RES_ALLOCATION_STATUS is '显示资源分配 1:可以查看资源分配，0不能查看资源分配';
comment on column IDC_TICKET_RUN.ROLE_KEY is '候选审批角色标识';
comment on column IDC_TICKET_RUN.SERIAL_NUMBER is '工单编号';
comment on column IDC_TICKET_RUN.TASK_ID is '任务主键';
comment on column IDC_TICKET_RUN.TASK_NAME is '任务名称';
comment on column IDC_TICKET_RUN.TICKET_UPDATE_STATUS is '工单是否可修改表单需求';
comment on column IDC_TICKET_RUN.TICKET_CATEGORY is '工单类型';
comment on column IDC_TICKET_RUN.TICKET_CATEGORY_FROM is '主键';
comment on column IDC_TICKET_RUN.TICKET_CATEGORY_TO is '主键';
comment on column IDC_TICKET_RUN.TICKET_RES_HAND_STATUS is '工单资源是否可编辑';
comment on column IDC_TICKET_RUN.TICKET_STATUS is '工单状态 0初始化、1运行中、-2作废、-3删除到回收站、2结束、-22作废结束、-23删除结束';
comment on column IDC_TICKET_RUN.SP_STATUS is '审批状态 -1不同意/驳回';
comment on column IDC_TICKET_RUN.IDC_CODE is '意向IDC的标识';
comment on column IDC_TICKET_RUN.REGION_ID is '工单所属区域主键';
comment on column IDC_TICKET_RUN.IDC_NAME is '意向IDC的名称';
comment on column IDC_TICKET_RUN.REGION_NAME is '工单所属区域名称';
comment on column IDC_TICKET_RUN.ROOT_ID is '受理工单主键';
comment on column IDC_TICKET_RUN.UPDATE_TIME is '修改日期';
comment on column IDC_TICKET_RUN.CONFIRM_STATUS is '确认状态';
COMMENT ON TABLE IDC_TICKET_TEST is '测试工单';
comment on column IDC_TICKET_TEST.ID is '主键';
comment on column IDC_TICKET_TEST.PROD_INST_ID is '订单实例主键';
comment on column IDC_TICKET_TEST.TICKET_INST_ID is '工单实例主键';
comment on column IDC_TICKET_TEST.TEST_END_TIME is '测试结束日期';
comment on column IDC_TICKET_TEST.TEST_START_TIME is '测试开始日期';
comment on column IDC_TICKET_TEST.VALIDITY is '测试有效期（天）';
